name: Install PDFtools

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r req.txt

      - name: Create executable
        run: |
          pip install pyinstaller
          pyinstaller --onefile --name pdftools pdftools.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: pdftools
          path: dist/pdftools.exe
